### ISSUE TITLE
[Lab 7] Continuous Delivery - Jenkins

### ISSUE THREAD

**Issue by stefinitu** [JS0Nderulo/service#27]
- [x] Add password and github tokens as environment variables in Jenkinsfile and configure Jenkins
- [x] Add Docker Compose stage and configure docker-compose.yml
- [x] Add Test stage with unit and integration tests

**Comment by Ana-Mares** [comment]
After trying to run the E2E tests locally, I found out that they are working (even though they are for the demo app, and not ours).
ToDo:
- [ ] Also add e2e tests stage in Jenkinsfile

**Comment by Ana-Mares** [comment]
> After trying to run the E2E tests locally, I found out that they are working (even though they are for the demo app, and not ours). ToDo:
> 
>     * [ ]  Also add e2e tests stage in Jenkinsfile


Tried to do this for several hours, couldn't get E2E tests to pass in jenkins builds:
- When ran locally, firstly the tests failed, but then they did pass
- In Jenkins, we get socket exceptions (different errors, mostly connection refused)
- With the app in the container, when accessing localhost:8080/hello-world, we get an error; if we go to other endpoints (for example, /avion, or /avion/1 etc), they will also return an error. <b>BUT when back button is pressed, the previous request will no longer return an error, it will return the expected response</b> -this only happens on my laptop; for @stefinitu the back workaround does not work
- Tried multiple possible fixes, nothing worked yet:
-- modified HelloApplication.java with the changes proposed in Issue 86  from the main Repo, as Razvan suggested (replace @SpringBootApplication to @SpringBootApplication(exclude={DataSourceAutoConfiguration.class}))
-- Added network_mode: host line in docker-compose.yml 
-- Modified the request headers in executeGet method from HelloWorldSteps.java
--  Explicitly added 0.0.0.0 and 127.0.0.1 to ports line in docker-compose.yml 
-- Set a proxy in getRestTemplate method from AppConfig.java to be used when running the tests
-- Some other local configs and troubleshooting (docker configs, trying telnet/ curl commands to access localhost:8080 from Linux and from the container etc.)

**Comment by Ana-Mares** [comment]
I accidentally closed it as complete. Will reopen in case we'll be able to fix it somehow, otherwise it shouldn't be closed as completed but as won't fix

**Comment by Ana-Mares** [comment]
Moved the E2E tests on a new issue as we couldn't fix it, but it would be best to close this original issue as completed and the e2e part as not completed.
